"""Añadir stock_minimo a Producto

Revision ID: 3ab025b067f0
Revises: d6907619dd5f
Create Date: 2025-10-16 11:01:35.051483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab025b067f0'
down_revision = 'd6907619dd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_minimo', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('stock_minimo')

    # ### end Alembic commands ###
