"""Permitir nombres de producto duplicados

Revision ID: 7accd896a33c
Revises: 3ab025b067f0
Create Date: 2025-10-20 09:52:59.533189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7accd896a33c'
down_revision = '3ab025b067f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_nombre'))
        batch_op.create_index(batch_op.f('ix_producto_nombre'), ['nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_nombre'))
        batch_op.create_index(batch_op.f('ix_producto_nombre'), ['nombre'], unique=True)

    # ### end Alembic commands ###
