"""Añadir índices de rendimiento para filtros

Revision ID: d6907619dd5f
Revises: 
Create Date: 2025-10-15 09:29:54.185779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6907619dd5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orden_estado'), ['estado'], unique=False)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_estado_fisico'), ['estado_fisico'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_ubicacion'), ['ubicacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_ubicacion_actual'), ['ubicacion_actual'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_unidad_medida'), ['unidad_medida'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_unidad_medida'))
        batch_op.drop_index(batch_op.f('ix_producto_ubicacion_actual'))
        batch_op.drop_index(batch_op.f('ix_producto_ubicacion'))
        batch_op.drop_index(batch_op.f('ix_producto_estado_fisico'))
        batch_op.drop_index(batch_op.f('ix_producto_estado'))

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orden_estado'))

    # ### end Alembic commands ###
